version: '3.8'

services:
  trading-calculator:
    image: nginx:alpine
    container_name: trading-calculator
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - trading-net

networks:
  trading-net:
    driver: bridge
